# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Signalverarbeitung 1
author: Joerg Bitzer

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: svscript.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - ../BibTex/AEC.bib       
  - ../BibTex/AESPaperForensik.bib  
  - ../BibTex/BeamGSC.bib  
  - ../BibTex/DEF.bib       
  - ../BibTex/FremdLit.bib   
  - ../BibTex/LIT.BIB                 
  - ../BibTex/Sonst.bib    
  - ../BibTex/speech.bib             
  - ../BibTex/wiener.bib
  - ../BibTex/AECandNR.bib  
  - ../BibTex/Audio.bib             
  - ../BibTex/Bitzer.bib   
  - ../BibTex/Forensik.bib  
  - ../BibTex/GSC_Promo.bib  
  - ../BibTex/publicationsBitzer.bib  
  - ../BibTex/SpecSub.bib  
  - ../BibTex/SpeechRecognition.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/JoergBitzer/Signalverarbeitung_Vorlesungsskript/  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
